name: agrix_africa_adt2025
description: AgriX Beta – Africa Deep Tech 2025 Smart Farmer App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Functionality
  image_picker: ^1.0.7           # Camera/gallery access
  tflite: ^1.1.2                 # On-device ML
  path_provider: ^2.1.2          # File paths
  file_picker: ^6.1.1            # File picker
  uuid: ^4.1.0                   # Unique IDs
  share_plus: ^7.2.1             # Share content
  intl: ^0.18.1                  # Date/time formatting
  url_launcher: ^6.2.5           # ✅ Launch tel:, sms:, mailto:, https:
  shared_preferences: ^2.2.2     # Persistent local storage
  flutter_secure_storage: ^9.0.0 # Encrypted secure storage

  # UI/UX Enhancements
  flutter_svg: ^2.0.9            # SVG support
  google_fonts: ^6.1.0           # Font customization
  font_awesome_flutter: ^10.7.0 # ✅ WhatsApp and social icons

  # QR and Biometrics
  qr_flutter: ^4.0.0             # QR generation
  local_auth: ^2.1.6             # Biometrics

  # Firebase (optional)
  firebase_core: ^2.24.2
  cloud_firestore: ^4.9.1

  # State Management
  provider: ^6.1.2

  # Encryption
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/alogo.png
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/alogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/alogo.png"
